### ISSUE TITLE
Adding the ability to add this library to multi-file projects

### ISSUE THREAD

**Issue by Voha888** [jrullan/StateMachine#11]
When creating a project in VScode with the Platformio plugin, it becomes necessary to re-include the library header file in several files, for example, to use the `extern` keyword.
The original version of the library does not allow this. I separated the class methods into **.cpp** files, now the library header files can be included in several compilation units.

Please, see my pull request #10

**Comment by jrullan** [comment]
Thank you for your contribution! Merged.

**Comment by ilianOptrel** [comment]
Release `1.0.13` incorporating this fix is not yet available on the PlatformIO registry. There, the current version is still `1.0.11`, so the library needs to be included via URL. Could you update to the newest release on PlatformIO registry?
