### ISSUE TITLE
transitionTo() not working?

### ISSUE THREAD

**Issue by MDRRC** [jrullan/StateMachine#6]
Hello

I use the transitionTo() like this

```
        else
        {
            XPNet.getLocoInfo(0, 3);
            stm.transitionTo(stPowerOn);
        }
```

but there is no state change... 

The state machine keeps in the state where it was as shown in the logging

> StateMachine::run() : 5
> StateGetLocInfo
> StateMachine::run() : 5
> StateMachine::transitionTo() : 3
> StateMachine::run() : 5

What I'm doing wrong?

**Comment by MDRRC** [comment]
"Fixed" it.

 * Added boolean transition and this is set to true in the transition functions

In run()

 ```
 if (this->transition ==false)
  {
    this->executeOnce = (this->currentState == next)?false:true;
    this->currentState = next;
  }
  else
  {
    this->transition = false;
  }
```

The `int next ` caused the problem, it was set to state x, when state transition was called it was still x ...

**Comment by HamzaHajeir** [comment]
Hi 

I had the same issue, It's now solved. Thanks for this.

But here I got another issue : 
Somewhere transitionTo makes the code stuck. I got no idea why.

**Comment by MDRRC** [comment]
Hi

 * Forked the state machine
 * Updated the code 
 * Updated the arduino_state_machine example.

Tested code on A Arduino Nano and runs.
